import { matchCharacter, samePerson } from "./cast";
import { effectiveScriptElementIds } from "./coverage-edit";
import type { Project, Shot, WorldEvent } from "./types";
import { SCENE_TARGET } from "./types";
import { EV_DLG, syncCoreEvents } from "./world";

const normalize = (text: string) => text.trim().replace(/\s+/g, " ");
const words = (text: string) => text.trim().split(/\s+/).filter(Boolean).length;

/** ev_dlg is regenerated by syncCoreEvents. A differing saved event may be authored. */
function isAutomaticDialogue(event: WorldEvent, shot: Shot): boolean {
  const expected = syncCoreEvents(shot).find((item) => item.id === EV_DLG);
  return (
    !!expected &&
    event.kind === "speech" &&
    event.text === expected.text &&
    (event.target === SCENE_TARGET ||
      event.target === (shot.characters[0] || SCENE_TARGET)) &&
    Math.abs(event.startSec - expected.startSec) < 1e-6 &&
    Math.abs(event.endSec - expected.endSec) < 1e-6
  );
}

function speakerLabel(raw: string, shot: Shot, project: Project): string {
  const offscreenCue = /\((?:O\.?S\.?|O\.?C\.?|V\.?O\.?)\)/i.test(raw);
  const name = raw
    .replace(/\s*\((?:O\.?S\.?|O\.?C\.?|V\.?O\.?|CONT['’]?D)\)/gi, "")
    .trim();
  const canonical = matchCharacter(project.characters, name)?.name ?? name;
  const onScreen =
    !offscreenCue &&
    shot.characters.some((cast) =>
      samePerson(project.characters, cast, canonical),
    );
  return `${canonical}${onScreen ? "" : " (off-screen)"}`;
}

/** Selected shot text is a take's dialogue; the wider coverage range only supplies attribution. */
function resolveDialogue(shot: Shot, project: Project) {
  const ids = new Set(effectiveScriptElementIds(project, shot));
  const source = project.script.filter(
    (element) => ids.has(element.id) && element.kind === "dialogue",
  );
  const selected = normalize(shot.dialogue);
  const matches: (typeof source)[] = [];
  for (let start = 0; start < source.length; start++) {
    let text = "";
    for (let end = start; end < source.length; end++) {
      text = [text, normalize(source[end].text)].filter(Boolean).join(" ");
      if (text === selected) matches.push(source.slice(start, end + 1));
      if (text.length >= selected.length) break;
    }
  }
  const signatures = new Set(
    matches.map((match) =>
      JSON.stringify(
        match.map((line) => [line.character?.trim(), normalize(line.text)]),
      ),
    ),
  );
  const match = signatures.size === 1 ? matches[0] : undefined;
  const unresolved = !match
    ? matches.length
      ? "is ambiguous in the selected coverage"
      : "does not match the linked screenplay dialogue"
    : match.some((line) => !line.character?.trim())
      ? "is missing a screenplay speaker"
      : "";
  if (unresolved)
    return {
      lines: [{ target: "Unattributed", text: shot.dialogue.trim() }],
      warning: `Dialogue attribution check: the selected dialogue ${unresolved}. Confirm the speaker and selected screenplay beats before generation; do not assign this speech to a visible character by default.`,
    };
  return {
    lines: match!.map((line) => ({
      target: speakerLabel(line.character!, shot, project),
      text: line.text,
    })),
    warning: "",
  };
}

/** Present corrected automatic speech without rewriting saved events, overrides or screenplay data. */
export function promptDialogue(
  shot: Shot,
  project: Project,
): { events: WorldEvent[]; direction: string } {
  const saved = shot.events?.length ? shot.events : syncCoreEvents(shot);
  const core = saved.find((event) => event.id === EV_DLG);
  const automatic = !core || isAutomaticDialogue(core, shot);
  let events = [...saved];
  let pendingSpeech: WorldEvent[] = [];
  const notes: string[] = [];
  if (automatic && shot.dialogue.trim()) {
    const resolved = resolveDialogue(shot, project);
    const timing =
      core ?? syncCoreEvents(shot).find((event) => event.id === EV_DLG)!;
    const count = resolved.lines.reduce(
      (total, line) => total + words(line.text),
      0,
    );
    let elapsedWords = 0;
    const speech = resolved.lines.map((line, index) => {
      const startSec =
        timing.startSec +
        ((timing.endSec - timing.startSec) * elapsedWords) / count;
      elapsedWords += words(line.text);
      return {
        ...timing,
        id: index === 0 ? EV_DLG : `${EV_DLG}_${index}`,
        ...line,
        startSec,
        endSec:
          timing.startSec +
          ((timing.endSec - timing.startSec) * elapsedWords) / count,
      };
    });
    if (resolved.warning) notes.push(resolved.warning);
    const available = Math.max(0, timing.endSec - timing.startSec);
    const oversized = count > available * 3;
    events = [
      ...saved.filter((event) => event.id !== EV_DLG),
      ...(oversized ? [] : speech),
    ];
    if (oversized) {
      // Retain every word as unscheduled source dialogue; never invent compressed timings.
      pendingSpeech = speech;
      notes.push(
        `Dialogue timing check: ${count} selected words need roughly ${(count / 3).toFixed(1)}s at 180 words/minute; only ${available.toFixed(1)}s is allocated inside this ${shot.durationSec}s take. This estimate excludes pauses and action and is not approved performance timing. Select a shorter screenplay passage or a supported longer take before generation. Do not accelerate delivery or omit words to fit.`,
        "Dialogue awaiting take selection (source order; no assigned times):",
        ...speech.map(
          (event) =>
            `[${event.target} speech] "${event.text.replace(/^["']|["']$/g, "")}"`,
        ),
      );
    }
  }
  const speech = [
    ...events.filter((event) => event.kind === "speech"),
    ...pendingSpeech,
  ];
  if (!speech.length) return { events, direction: "No dialogue." };
  notes.unshift(
    "Speak only the dialogue in the named speech events; keep off-screen voices out of frame.",
  );
  const silent = shot.characters.filter(
    (name) =>
      !speech.some(
        (event) =>
          !event.target.endsWith(" (off-screen)") &&
          samePerson(project.characters, name, event.target),
      ),
  );
  if (silent.length)
    notes.push(
      `On-screen characters without speech events remain silent: ${silent.join(", ")}.`,
    );
  const offscreen = [
    ...new Set(
      speech.flatMap((event) => {
        const name = event.target.replace(/ \(off-screen\)$/, "");
        if (name === SCENE_TARGET || name === "Unattributed") return [];
        return event.target.endsWith(" (off-screen)") ||
          !shot.characters.some((cast) =>
            samePerson(project.characters, cast, name),
          )
          ? [name]
          : [];
      }),
    ),
  ];
  if (offscreen.length)
    notes.push(
      `Off-screen speakers: ${offscreen.join(", ")}. Voices only; do not add them to the frame.`,
    );
  for (const name of offscreen) {
    const voice = matchCharacter(project.characters, name)?.voice;
    if (voice) notes.push(`Off-screen voice — ${name}: ${voice}`);
  }
  return { events, direction: notes.join("\n") };
}
