import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {test} from 'node:test';
const require=createRequire(import.meta.url), ts=require('typescript'), React=require('react');
const source=ts.createSourceFile('frame-studio.tsx',readFileSync(new URL('../src/components/app/frame-studio.tsx',import.meta.url),'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
let action,editAction,continueAction;
function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(source)==='capturePlan')action=n.initializer;if(ts.isJsxAttribute(n)&&n.name.getText(source)==='onClick'){const button=n.parent?.parent?.parent?.getText(source)??'';if(button.includes('Edit current frame'))editAction=n.initializer.expression;if(button.includes('Use previous reference'))continueAction=n.initializer.expression;}ts.forEachChild(n,visit);}visit(source);
const code=ts.transpileModule(`const action=${action.getText(source)};`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
function setup(){let finish;const settings={guides:false,wireframe:true,markup:false,image:true,onionSkinOpacity:.3};const shot={id:'s'},project={id:'p',shots:[shot,{id:'other'}]},calls=[],saved={guide:null,overhead:'old',placement:'old',image:'old'},errors=[];const scope={project,shot,compositionPreview:false,frameLayers:settings,compositionContext:{current:{projectId:'p',shotId:'s',frameLayers:settings,compositionPreview:false}},mounted:{current:true},stageGate:{ready:true,issues:[]},formatGateIssues:()=>'',toast:{error:value=>errors.push(value),success:()=>{}},setBusy:()=>{},useSlate:{getState:()=>({project,selectedId:"s"})},capturePlanComposition:(...args)=>{calls.push(args);return new Promise(r=>{finish=r;});},setPlanGuide:value=>saved.guide=value,setOverheadReview:value=>saved.overhead=value,setPlacementReview:value=>saved.placement=value,setImageReview:value=>saved.image=value};return{scope,calls,saved,errors,finish:()=>finish?.({layers:settings}),run:new Function(...Object.keys(scope),code+'return action;')(...Object.values(scope))};}
test('local plan capture passes exact visible settings and clears prior approvals',async()=>{const s=setup(),p=s.run();assert.equal(s.calls[0][2],s.scope.frameLayers);s.finish();await p;assert.deepEqual(s.saved.guide,{layers:s.scope.frameLayers});assert.equal(s.saved.overhead,null);assert.equal(s.saved.placement,null);assert.equal(s.saved.image,null);});
for(const change of ['layers','selection','unmount','project'])test(`plan capture rejects ${change} changing while capture loads`,async()=>{const s=setup(),p=s.run();if(change==='layers')s.scope.compositionContext.current.frameLayers={...s.scope.frameLayers,markup:true};if(change==='selection')s.scope.useSlate.getState=()=>({project:s.scope.project,selectedId:'other'});if(change==='unmount')s.scope.mounted.current=false;if(change==='project')s.scope.useSlate.getState=()=>({project:{id:'other',shots:[]},selectedId:'s'});s.finish();await p;assert.match(s.errors.at(-1),/changed/);assert.equal(s.calls.length,1);assert.equal(s.saved.guide,null);});
// Render actual parent JSX with controlled React hooks; no browser or network calls.
for(const [file,component] of [['frame-studio.tsx','FrameStudio'],['blocking-studio.tsx','BlockingStudio']])test(`${component} shares the same settings and setter with canvas and actions`,()=>{
 const text=readFileSync(new URL(`../src/components/app/${file}`,import.meta.url),'utf8'),sf=ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
 const node=sf.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===component);
 const compiled=ts.transpileModule(node.getText(sf).replace('export function','function'),{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText;
 const settings={guides:true,wireframe:true,markup:false,image:true,onionSkinOpacity:.4},setter=()=>{};
 const scope={React,useStagePlayback:fn=>fn({playing:false,shotClock:0,shotProgress:0,shotId:null}),DEFAULT_FRAME_LAYERS:settings,useState:x=>x===settings?[settings,setter]:[x==='plan'?'frame':x,()=>{}],useEffect:()=>{},useRef:()=>({current:null}),useSlate:fn=>fn({project:{id:'p',floor:{}},setSketch:()=>{},setAnnotations:()=>{}}),cameraForShot:()=>null,figuresForShot:()=>[],originalOverheadFor:()=>null,originalBoardFor:()=>null,poseAt:()=>null,poseCameraAt:()=>null,PANES:[],CAMERA_MOVEMENTS:[],MOVEMENT_LABELS:{},cn:()=>''};
 for(const name of ['BlockingCanvas','ImagineActions','OriginalInset','OverheadPlan','CastRail','StagePromptCard','DropdownMenu','DropdownMenuTrigger','DropdownMenuContent','DropdownMenuItem','Button','ChevronDown','Image','Pause','Play','ChevronRight','Video','Layers','RotateCw','COVERAGE_DOCK_OPEN_EVENT'])scope[name]=name;
 const render=new Function(...Object.keys(scope),compiled+`return ${component};`)(...Object.values(scope));
 const tree=render({shot:{id:'s',sketch:{stamps:[]},annotations:[]},shots:[]});
 const nodes=n=>!n||typeof n!=='object'?[]:[n,...React.Children.toArray(n.props?.children).flatMap(nodes)];const all=nodes(tree),canvas=all.find(n=>n.type==='BlockingCanvas'),actions=all.find(n=>n.type==='ImagineActions');assert.ok(canvas&&actions);assert.equal(canvas.props.layers,settings);assert.equal(canvas.props.onLayersChange,setter);assert.equal(actions.props.frameLayers,settings);
});

test('live selected setup changing without render rejects capture completion',async()=>{const s=setup(),p=s.run();s.scope.useSlate.getState=()=>({project:s.scope.project,selectedId:'other'});s.finish();await p;assert.match(s.errors.at(-1),/changed/);assert.equal(s.calls.length,1);});
test('absent selection follows the existing first setup fallback',async()=>{const s=setup();s.scope.useSlate.getState=()=>({project:s.scope.project,selectedId:null});const p=s.run();s.finish();await p;assert.deepEqual(s.saved.guide,{layers:s.scope.frameLayers});});

function runEdit(imageReview){const calls=[],scope={run:(_label,fn)=>fn(),restyleShotFrame:(...args)=>calls.push(args),shot:{id:'s'},direction:'Warmer',options:{connectionId:'cloud'},imageReview,imageReviewFingerprint:'current-review'};const compiled=ts.transpileModule(`const action=${editAction.getText(source)};`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;const run=new Function(...Object.keys(scope),compiled+'return action;')(...Object.values(scope));run();return calls[0][2];}
test('Edit current frame passes the exact explicit image review into the paid edit',()=>assert.deepEqual(runEdit('current-review'),{connectionId:'cloud',imageReviewFingerprint:'current-review'}));
test('Edit current frame never substitutes a computed fingerprint for absent explicit review',()=>assert.deepEqual(runEdit(null),{connectionId:'cloud',imageReviewFingerprint:null}));
function runContinue(imageReview){const calls=[],scope={run:(_label,fn)=>fn(),continueFromPrevious:(...args)=>calls.push(args),shot:{id:'s'},options:{connectionId:'cloud'},imageReview,previousReviewFingerprint:'previous-review'};const compiled=ts.transpileModule(`const action=${continueAction.getText(source)};`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;const run=new Function(...Object.keys(scope),compiled+'return action;')(...Object.values(scope));run();return calls[0][1];}
test('Use previous reference passes the exact explicit image review into the paid continuation',()=>assert.deepEqual(runContinue('previous-review'),{connectionId:'cloud',imageReviewFingerprint:'previous-review'}));
test('Use previous reference never substitutes a computed fingerprint for absent explicit review',()=>assert.deepEqual(runContinue(null),{connectionId:'cloud',imageReviewFingerprint:null}));
